Introdutórias:

1. Crie um array com 4 linhas e 3 colunas com valores aleatórios.
2. Crie um array com valores inteiros, 3 linhas e 5 colunas com valores aleatórios.
3. Crie um array com 5 colunas e 10 linhas inicializados com zeros. 
4. Crie um array que vá entre 0 e 90 pulando de 4 em 4.
5. Reduza o array(5,7) a apenas uma dimensão.
6. Considerando que você é uma organizadora de um jogo de bingo. Crie um array que irá representar a cartilha desses jogos de bingo, os números das suas cartelas variam entre 1 e 30, e você terá 10 participantes. Cada cartela terá 12 números(4,3). Crie um array que representa esse jogo.
7. Faça o reshape das suas cartelas para que haja 5 cartelas de 4 linhas e 6 colunas.

In [1]:
import numpy as np

In [2]:
#1. Crie um array com 4 linhas e 3 colunas com valores aleatórios.

arr = np.random.random((4,3))
arr 

array([[0.24100227, 0.72564721, 0.34232325],
       [0.77279467, 0.1859839 , 0.90138988],
       [0.09907901, 0.71326931, 0.44060581],
       [0.36738495, 0.55511792, 0.51627972]])

In [3]:
#2. Crie um array com valores inteiros, 3 linhas e 5 colunas com valores aleatórios.
arr = np.random.randint(10, 30, size=(3,5))
arr

array([[25, 11, 26, 24, 28],
       [20, 17, 14, 13, 21],
       [11, 27, 27, 11, 16]])

In [4]:
#3. Crie um array com 5 colunas e 10 linhas inicializados com zeros. 
arr = np.zeros((10,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
#4. Crie um array que vá entre 0 e 90 pulando de 4 em 4.
arr = np.arange(0, 91, 4)
arr

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76, 80, 84, 88])

In [6]:
#5. Reduza o array(5,7) a apenas uma dimensão.
arr = np.random.randint(10, 30, size=(5,7))
print (arr)
arr = arr.flatten()
arr

[[11 21 14 18 20 17 24]
 [11 15 28 16 18 28 10]
 [24 16 18 27 20 12 16]
 [14 16 17 23 21 17 21]
 [23 23 26 21 26 16 27]]


array([11, 21, 14, 18, 20, 17, 24, 11, 15, 28, 16, 18, 28, 10, 24, 16, 18,
       27, 20, 12, 16, 14, 16, 17, 23, 21, 17, 21, 23, 23, 26, 21, 26, 16,
       27])

In [7]:
#6. Considerando que você é uma organizadora de um jogo de bingo. 
#Crie um array que irá representar a cartilha desses jogos de bingo, 
#os números das suas cartelas variam entre 1 e 30, e você terá 10 participantes. 
#Cada cartela terá 10 números(4,3). Crie um array que representa esse jogo.

bingo = np.random.randint(1, 31, size=(10, 4, 3))
bingo

array([[[13, 10, 11],
        [ 8, 21, 29],
        [15,  1, 25],
        [11, 25, 16]],

       [[ 3, 24,  6],
        [28, 21, 17],
        [18,  1,  8],
        [27, 27, 13]],

       [[28,  8, 12],
        [ 1, 29, 25],
        [ 8, 22, 10],
        [11, 14, 17]],

       [[22,  9,  5],
        [14,  3,  1],
        [15, 25,  3],
        [19, 24, 20]],

       [[28,  8,  9],
        [ 7, 29, 13],
        [ 6, 20, 15],
        [18,  8, 12]],

       [[ 4, 23,  3],
        [11, 16, 27],
        [18, 19, 23],
        [13, 11, 26]],

       [[ 3,  8,  5],
        [29, 26, 18],
        [ 1, 11, 16],
        [28,  5,  2]],

       [[16,  7, 27],
        [12, 19, 29],
        [ 9,  5, 28],
        [29, 20, 18]],

       [[15, 18,  9],
        [ 8, 23,  5],
        [14, 26,  4],
        [10,  1,  4]],

       [[13,  3,  9],
        [12,  6, 15],
        [ 4,  7, 14],
        [30, 15,  4]]])

In [8]:
#7. Faça o reshape das suas cartelas para que haja 5 cartelas de 4 linhas e 6 colunas.
bingo.reshape((5,4,6))

array([[[13, 10, 11,  8, 21, 29],
        [15,  1, 25, 11, 25, 16],
        [ 3, 24,  6, 28, 21, 17],
        [18,  1,  8, 27, 27, 13]],

       [[28,  8, 12,  1, 29, 25],
        [ 8, 22, 10, 11, 14, 17],
        [22,  9,  5, 14,  3,  1],
        [15, 25,  3, 19, 24, 20]],

       [[28,  8,  9,  7, 29, 13],
        [ 6, 20, 15, 18,  8, 12],
        [ 4, 23,  3, 11, 16, 27],
        [18, 19, 23, 13, 11, 26]],

       [[ 3,  8,  5, 29, 26, 18],
        [ 1, 11, 16, 28,  5,  2],
        [16,  7, 27, 12, 19, 29],
        [ 9,  5, 28, 29, 20, 18]],

       [[15, 18,  9,  8, 23,  5],
        [14, 26,  4, 10,  1,  4],
        [13,  3,  9, 12,  6, 15],
        [ 4,  7, 14, 30, 15,  4]]])

Manipulando Arrays 
1. Explorando Ecossistemas: 
Como bióloga marinha, me encontrei em uma expedição nas profundezas do Oceano Pacífico, onde estávamos estudando a biodiversidade e a saúde dos recifes de coral. O catálogo abaixo demonstra dados das espécies encontradas. Considere a seguinte ordem de colunas:

*ID da espécie, quantidade de representantes encontrados, profundeza, tamanho médio da espécie.*

a. Selecione a segunda coluna com a quantidade de espécies encontradas e adicione em um array as qtd_especies.

b. De qtd_especies selecione apenas as primeiras 3 quantidades e print.

c. Print as 5 últimas quantidades de espécies.

d.Crie um array que contenha apenas os tamanhos das espécies e ordene por ordem crescente.

In [9]:
especies = np.array([
                    [747,  89, 33,  5],
                    [623, 123, 32, 13],
                    [501,  22, 49,  2],
                    [116, 101, 42, 10],
                    [297,  56, 69, 22],
                    [613,  64, 27,  7],
                    [295,  84, 29, 14],
                    [692, 105, 72, 16],
                    [229, 103, 35,  5],
                    [374, 124, 70,  1]
                    ])

In [10]:
#a. Selecione a segunda coluna com a quantidade de espécies encontradas e adicione em um array as qtd_especies.
qtd_especies = especies[:,1]
qtd_especies

array([ 89, 123,  22, 101,  56,  64,  84, 105, 103, 124])

In [11]:
#b. De qtd_especies selecione apenas as primeiras 3 quantidades e print.
qtd_especies[0:3]

array([ 89, 123,  22])

In [12]:
#c. Print as 5 últimas quantidades de espécies.
qtd_especies[-5:]

array([ 64,  84, 105, 103, 124])

In [13]:
#d.Crie um array que contenha apenas os tamanhos das espécies e ordene por ordem crescente.
np.sort(especies[:,3])

array([ 1,  2,  5,  5,  7, 10, 13, 14, 16, 22])

2. Ainda usando o Array de espécies marítimas.
a. Usando um index boolean crie um array que contém os dados da maior espécie encontrada(considerando o seu tamanho),esse valor corresponde ao valor 22.

b. Usando fency index faça um array que contém apenas dados da espécie com ID297.

c. Usando np.where() faça um array com a linha com dados correspondentes a espécie com 105 representantes encontrados.

d. Considere a profundeza em que o espécie foi encontrada substitua valores maiores que 60 com "Profundo”


In [14]:
#a. Usando um index boolean crie um array que contém os dados da maior espécie encontrada(considerando o seu tamanho),
#esse valor corresponde ao valor 22.

especies[especies[:,3]==22]

array([[297,  56,  69,  22]])

In [15]:
#b. Usando fency index faça um array que contém apenas dados da espécie com ID297.

mask_297 = especies[:,0]==297
especies[mask_297]

array([[297,  56,  69,  22]])

In [16]:
#c. Usando np.where() faça um array com a linha com dados correspondentes a espécie com 105 representantes encontrados.

especies[np.where(especies[:, 1]==105)]

array([[692, 105,  72,  16]])

In [17]:
#d. Considere a profundeza em que o espécie foi encontrada substitua valores maiores que 60 com "Profundo”
np.where(especies[:,2]>60, "Profundo", especies[:,2])

array(['33', '32', '49', '42', 'Profundo', '27', '29', 'Profundo', '35',
       'Profundo'], dtype='<U11')

3. Ainda no conjunto 'especies'.

a. Adicione mais 2 espécies ao array:[[204,10,40,12],[392,11,81,11]].

b. Adicione mais uma coluna no array original agora com o número de espécies encontradas com que indica se o animal enxerga ou não: [0,1,0,0,0,0,1,0,1,1]

In [18]:
#a. Adicione mais 2 espécies ao array:[[204,10,40,12],[392,11,81,11]].

novas_especies = np.array([
                            [204, 10, 40, 12],
                            [392, 11, 81, 11]]
                            )

np.concatenate((especies, novas_especies))

array([[747,  89,  33,   5],
       [623, 123,  32,  13],
       [501,  22,  49,   2],
       [116, 101,  42,  10],
       [297,  56,  69,  22],
       [613,  64,  27,   7],
       [295,  84,  29,  14],
       [692, 105,  72,  16],
       [229, 103,  35,   5],
       [374, 124,  70,   1],
       [204,  10,  40,  12],
       [392,  11,  81,  11]])

In [19]:
#b. Adicione mais uma coluna no array original agora com o número de espécies encontradas 
#com que indica se o animal enxerga ou não: [0,1,0,0,0,0,1,0,1,1]
especies_ver = np.array([0,1,0,0,0,0,1,0,1,1]).reshape(10,1)
np.concatenate((especies, especies_ver), axis=1)

array([[747,  89,  33,   5,   0],
       [623, 123,  32,  13,   1],
       [501,  22,  49,   2,   0],
       [116, 101,  42,  10,   0],
       [297,  56,  69,  22,   0],
       [613,  64,  27,   7,   0],
       [295,  84,  29,  14,   1],
       [692, 105,  72,  16,   0],
       [229, 103,  35,   5,   1],
       [374, 124,  70,   1,   1]])

Salvando array

In [24]:
arr2d = np.array([[1,2,3], [4,5,6]])
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
arr3d = np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]])
arr3d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [26]:
#Salvando txt
np.savetxt('array2d', arr2d, delimiter=',')

In [28]:
#Salvando csv
np.savetxt('array2d.csv', arr2d, delimiter=',')

In [29]:
#Salvando 3d, que nao pode ser salvo como txt ou csv

np.save('array3d', arr3d)

In [30]:
#Carregando o arquivo
arrload = np.load('array3d.npy')
arrload

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

Cálculo com Array 

Considerando o array abaixo, responda

In [20]:
acidentes = np.array([
                     [1, 3, 2],
                     [0, 1, 0],
                     [2, 1, 4],
                     [0, 0, 0],
                     [1, 1, 0]
                     ])