Introdutórias:

1. Crie um array com 4 linhas e 3 colunas com valores aleatórios.
2. Crie um array com valores inteiros, 3 linhas e 5 colunas com valores aleatórios.
3. Crie um array com 5 colunas e 10 linhas inicializados com zeros. 
4. Crie um array que vá entre 0 e 90 pulando de 4 em 4.
5. Reduza o array(5,7) a apenas uma dimensão.
6. Considerando que você é uma organizadora de um jogo de bingo. Crie um array que irá representar a cartilha desses jogos de bingo, os números das suas cartelas variam entre 1 e 30, e você terá 10 participantes. Cada cartela terá 12 números(4,3). Crie um array que representa esse jogo.
7. Faça o reshape das suas cartelas para que haja 5 cartelas de 4 linhas e 6 colunas.

In [35]:
import numpy as np

In [36]:
#1. Crie um array com 4 linhas e 3 colunas com valores aleatórios.

arr = np.random.random((4,3))
arr 

array([[0.05998969, 0.4760945 , 0.48750266],
       [0.4935142 , 0.86612112, 0.67151896],
       [0.87172233, 0.21095284, 0.81864949],
       [0.33068614, 0.83906474, 0.08761206]])

In [37]:
#2. Crie um array com valores inteiros, 3 linhas e 5 colunas com valores aleatórios.
arr = np.random.randint(10, 30, size=(3,5))
arr

array([[27, 10, 17, 11, 14],
       [22, 20, 10, 16, 24],
       [22, 19, 10, 18, 12]])

In [38]:
#3. Crie um array com 5 colunas e 10 linhas inicializados com zeros. 
arr = np.zeros((10,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [39]:
#4. Crie um array que vá entre 0 e 90 pulando de 4 em 4.
arr = np.arange(0, 91, 4)
arr

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76, 80, 84, 88])

In [40]:
#5. Reduza o array(5,7) a apenas uma dimensão.
arr = np.random.randint(10, 30, size=(5,7))
print (arr)
arr = arr.flatten()
arr

[[10 19 13 21 13 27 14]
 [26 26 26 10 27 14 28]
 [26 26 23 17 26 18 17]
 [17 17 25 21 11 20 24]
 [27 21 29 10 23 14 25]]


array([10, 19, 13, 21, 13, 27, 14, 26, 26, 26, 10, 27, 14, 28, 26, 26, 23,
       17, 26, 18, 17, 17, 17, 25, 21, 11, 20, 24, 27, 21, 29, 10, 23, 14,
       25])

In [41]:
#6. Considerando que você é uma organizadora de um jogo de bingo. 
#Crie um array que irá representar a cartilha desses jogos de bingo, 
#os números das suas cartelas variam entre 1 e 30, e você terá 10 participantes. 
#Cada cartela terá 10 números(4,3). Crie um array que representa esse jogo.

bingo = np.random.randint(1, 31, size=(10, 4, 3))
bingo

array([[[22, 17, 19],
        [ 9,  8, 20],
        [ 2,  4, 17],
        [28,  1, 30]],

       [[23, 26,  7],
        [ 1,  5, 11],
        [ 7,  6, 30],
        [29,  5, 27]],

       [[21,  2,  7],
        [ 9, 14, 22],
        [ 4, 14, 30],
        [ 6, 27, 27]],

       [[ 7,  6, 20],
        [27, 21, 20],
        [28, 24,  4],
        [16, 10, 27]],

       [[27, 18, 26],
        [ 9, 25, 20],
        [22,  3, 24],
        [13,  7,  1]],

       [[30,  1, 11],
        [16, 10,  9],
        [23, 25,  2],
        [ 4, 24, 16]],

       [[24,  5,  4],
        [23,  9, 23],
        [ 3, 12, 21],
        [13, 17, 23]],

       [[ 3, 27, 20],
        [28,  3, 12],
        [25, 26, 30],
        [16, 22,  1]],

       [[12, 19, 12],
        [25, 10,  9],
        [30,  2, 15],
        [14, 13,  6]],

       [[26, 14, 25],
        [29, 17,  4],
        [19, 23,  9],
        [ 7, 12, 22]]])

In [42]:
#7. Faça o reshape das suas cartelas para que haja 5 cartelas de 4 linhas e 6 colunas.
bingo.reshape((5,4,6))

array([[[22, 17, 19,  9,  8, 20],
        [ 2,  4, 17, 28,  1, 30],
        [23, 26,  7,  1,  5, 11],
        [ 7,  6, 30, 29,  5, 27]],

       [[21,  2,  7,  9, 14, 22],
        [ 4, 14, 30,  6, 27, 27],
        [ 7,  6, 20, 27, 21, 20],
        [28, 24,  4, 16, 10, 27]],

       [[27, 18, 26,  9, 25, 20],
        [22,  3, 24, 13,  7,  1],
        [30,  1, 11, 16, 10,  9],
        [23, 25,  2,  4, 24, 16]],

       [[24,  5,  4, 23,  9, 23],
        [ 3, 12, 21, 13, 17, 23],
        [ 3, 27, 20, 28,  3, 12],
        [25, 26, 30, 16, 22,  1]],

       [[12, 19, 12, 25, 10,  9],
        [30,  2, 15, 14, 13,  6],
        [26, 14, 25, 29, 17,  4],
        [19, 23,  9,  7, 12, 22]]])

Manipulando Arrays 
1. Explorando Ecossistemas: 
Como bióloga marinha, me encontrei em uma expedição nas profundezas do Oceano Pacífico, onde estávamos estudando a biodiversidade e a saúde dos recifes de coral. O catálogo abaixo demonstra dados das espécies encontradas. Considere a seguinte ordem de colunas:

*ID da espécie, quantidade de representantes encontrados, profundeza, tamanho médio da espécie.*

a. Selecione a segunda coluna com a quantidade de espécies encontradas e adicione em um array as qtd_especies.

b. De qtd_especies selecione apenas as primeiras 3 quantidades e print.

c. Print as 5 últimas quantidades de espécies.

d.Crie um array que contenha apenas os tamanhos das espécies e ordene por ordem crescente.

In [43]:
especies = np.array([
                    [747,  89, 33,  5],
                    [623, 123, 32, 13],
                    [501,  22, 49,  2],
                    [116, 101, 42, 10],
                    [297,  56, 69, 22],
                    [613,  64, 27,  7],
                    [295,  84, 29, 14],
                    [692, 105, 72, 16],
                    [229, 103, 35,  5],
                    [374, 124, 70,  1]
                    ])

In [44]:
#a. Selecione a segunda coluna com a quantidade de espécies encontradas e adicione em um array as qtd_especies.
qtd_especies = especies[:,1]
qtd_especies

array([ 89, 123,  22, 101,  56,  64,  84, 105, 103, 124])

In [45]:
#b. De qtd_especies selecione apenas as primeiras 3 quantidades e print.
qtd_especies[0:3]

array([ 89, 123,  22])

In [46]:
#c. Print as 5 últimas quantidades de espécies.
qtd_especies[-5:]

array([ 64,  84, 105, 103, 124])

In [47]:
#d.Crie um array que contenha apenas os tamanhos das espécies e ordene por ordem crescente.
np.sort(especies[:,3])

array([ 1,  2,  5,  5,  7, 10, 13, 14, 16, 22])

2. Ainda usando o Array de espécies marítimas.
a. Usando um index boolean crie um array que contém os dados da maior espécie encontrada(considerando o seu tamanho),esse valor corresponde ao valor 22.

b. Usando fency index faça um array que contém apenas dados da espécie com ID297.

c. Usando np.where() faça um array com a linha com dados correspondentes a espécie com 105 representantes encontrados.

d. Considere a profundeza em que o espécie foi encontrada substitua valores maiores que 60 com "Profundo”


In [48]:
#a. Usando um index boolean crie um array que contém os dados da maior espécie encontrada(considerando o seu tamanho),
#esse valor corresponde ao valor 22.

especies[especies[:,3]==22]

array([[297,  56,  69,  22]])

In [49]:
#b. Usando fency index faça um array que contém apenas dados da espécie com ID297.

mask_297 = especies[:,0]==297
especies[mask_297]

array([[297,  56,  69,  22]])

In [50]:
#c. Usando np.where() faça um array com a linha com dados correspondentes a espécie com 105 representantes encontrados.

especies[np.where(especies[:, 1]==105)]

array([[692, 105,  72,  16]])

In [51]:
#d. Considere a profundeza em que o espécie foi encontrada substitua valores maiores que 60 com "Profundo”
np.where(especies[:,2]>60, "Profundo", especies[:,2])

array(['33', '32', '49', '42', 'Profundo', '27', '29', 'Profundo', '35',
       'Profundo'], dtype='<U11')

3. Ainda no conjunto 'especies'.

a. Adicione mais 2 espécies ao array:[[204,10,40,12],[392,11,81,11]].

b. Adicione mais uma coluna no array original agora com o número de espécies encontradas com que indica se o animal enxerga ou não: [0,1,0,0,0,0,1,0,1,1]

In [52]:
#a. Adicione mais 2 espécies ao array:[[204,10,40,12],[392,11,81,11]].

novas_especies = np.array([
                            [204, 10, 40, 12],
                            [392, 11, 81, 11]]
                            )

np.concatenate((especies, novas_especies))

array([[747,  89,  33,   5],
       [623, 123,  32,  13],
       [501,  22,  49,   2],
       [116, 101,  42,  10],
       [297,  56,  69,  22],
       [613,  64,  27,   7],
       [295,  84,  29,  14],
       [692, 105,  72,  16],
       [229, 103,  35,   5],
       [374, 124,  70,   1],
       [204,  10,  40,  12],
       [392,  11,  81,  11]])

In [58]:
#b. Adicione mais uma coluna no array original agora com o número de espécies encontradas 
#com que indica se o animal enxerga ou não: [0,1,0,0,0,0,1,0,1,1]
especies_ver = np.array([0,1,0,0,0,0,1,0,1,1]).reshape(10,1)
np.concatenate((especies, especies_ver), axis=1)

array([[747,  89,  33,   5,   0],
       [623, 123,  32,  13,   1],
       [501,  22,  49,   2,   0],
       [116, 101,  42,  10,   0],
       [297,  56,  69,  22,   0],
       [613,  64,  27,   7,   0],
       [295,  84,  29,  14,   1],
       [692, 105,  72,  16,   0],
       [229, 103,  35,   5,   1],
       [374, 124,  70,   1,   1]])

Cálculo com Array 

Considerando o array abaixo, responda

In [59]:
acidentes = np.array([
                     [1, 3, 2],
                     [0, 1, 0],
                     [2, 1, 4],
                     [0, 0, 0],
                     [1, 1, 0]
                     ])

1. O cliente que teve acidente abaixo da média nos últimos 2anos, ganhará um desconto no seu seguro. Identifique-os.
2. Qual cliente teve pelo menos 2 anos sem cometer acidentes? 
3. Uma professora quer que seus alunos apliquem a função (3x+2y+x*y) em um conjunto de dados. Ela dá dois arrays aos estudantes e pede que se ja feita essa operação.
4. A mesma professora percebeu que houve um erro em todas asprovas dos estudantes e esqueceu de anotar a nota de trabalhos apresenta dos durante o semestre. Já que foi feito em grupo ela vai adicionar a mesma nota para todos os estudantes. No array cada estudante representa uma linha e cada coluna uma prova. Adicione para cada prova de cada estudante os valores:1, 2, 1