In [1]:
import numpy as np

In [2]:
l = [1, 2, 3, 4]

In [3]:
arr1 = np.array(l)
arr1

array([1, 2, 3, 4])

In [4]:
#Criando um numpy array do zero
a = np.zeros((2,2)) #recebe uma tupla 2x2
a

array([[0., 0.],
       [0., 0.]])

In [5]:
b = np.arange(0,3) #sinaliza onde inicializa e onde termina -1
b

array([0, 1, 2])

In [6]:
c = np.random.random((3,3)) #recebe uma tupla randonica
c

array([[0.54783893, 0.71789657, 0.86975425],
       [0.28364779, 0.10431014, 0.13582276],
       [0.62018378, 0.07999213, 0.19053351]])

1. Crie um array com 4 linhas e 3 colunas com valores aleatórios

In [7]:
arrayRandom = np.random.random((4,3))
arrayRandom

array([[0.4309007 , 0.2744321 , 0.03809759],
       [0.82227574, 0.43706454, 0.76976   ],
       [0.80017832, 0.92714393, 0.76482884],
       [0.8413781 , 0.52633137, 0.5245777 ]])

2. Crie um array com 5 colunas e 10 linhas inicializados com zeros

In [8]:
arrayZero = np.zeros((10,5))
arrayZero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

3. Crie um array com valoes inteiros com 3 linhas e 5 colunas com valores aleatórios

In [9]:
arrayRandomInteiro = np.random.randint(10, 30, size=(3,5)) #valores aleatórios a partir do 10 até 29
arrayRandomInteiro

array([[21, 26, 13, 22, 25],
       [13, 18, 26, 20, 23],
       [17, 23, 12, 13, 16]])

In [10]:
#Array 3D

arr1_2d = np.array([[1,2],[3,4]])
arr2_2d = np.array([[5,6],[7,8]])
arr3_2d = np.array([[9,2],[3,4]])

arr_3d = np.array([arr1_2d, arr2_2d, arr3_2d])
arr_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]],

       [[9, 2],
        [3, 4]]])

In [11]:
#Shape -> quantas dimensões
arrShape = np.zeros((2,4))
print (arrShape)

arrShape.shape

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


(2, 4)

In [12]:
#Flatten -> achatando a matriz
arrFlatten = np.array ([[1,2,3,3], [4,5,6,6], [7,8,9,9]])
print (arrFlatten)

arrFlatten.flatten()

[[1 2 3 3]
 [4 5 6 6]
 [7 8 9 9]]


array([1, 2, 3, 3, 4, 5, 6, 6, 7, 8, 9, 9])

In [13]:
#Reshape -> mudando as dimensões
arrReshape = np.array([[3,4,2], [8,11,5]])
print ('array padrão')
print (arrReshape)

#O reshape sempre deve ser compativel com a quantidade de elementos, por exemplo:
print ('sempre deve ser compativel com a quantidade de elementos, o exemplo acima é 2x3, ou seja, 6 elementos, por isso:')
print ('array 3x2')
print(arrReshape.reshape((3,2)))
print ('array 6x1')
print(arrReshape.reshape((6,1)))

array padrão
[[ 3  4  2]
 [ 8 11  5]]
sempre deve ser compativel com a quantidade de elementos, o exemplo acima é 2x3, ou seja, 6 elementos, por isso:
array 3x2
[[ 3  4]
 [ 2  8]
 [11  5]]
array 6x1
[[ 3]
 [ 4]
 [ 2]
 [ 8]
 [11]
 [ 5]]


4. Reduza o array (5,7) a apenas uma dimensão

In [14]:
array4 = np.zeros((5,7))
print (array4)

print ('transformando para uma dimensão: ')
array4 = array4.flatten()
print(array4)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
transformando para uma dimensão: 
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


5. Considerando que você é uma organizadora de um jogo de bingo, crie um array que irá representar a cartilha desses jogos de bingo. Os números de suas cartelas variam entre 1 a 30, e você terá 10 participantes. Cada cartela terá 12 números (4,3).

Crie um array que represente esse jogo:

In [15]:
bingo = np.random.randint(1,31, size=(10,4,3))
print(bingo)

[[[ 4  6 22]
  [ 1  2 11]
  [14 18 24]
  [14 18 18]]

 [[ 3 13  8]
  [ 7 15 19]
  [23  4  1]
  [16 16  7]]

 [[ 4 15  9]
  [29 18  5]
  [26 28  4]
  [26 23 27]]

 [[26 12  4]
  [11  8  4]
  [20  1  3]
  [22  2  1]]

 [[16 26 11]
  [16 25  6]
  [30 18  9]
  [ 8 16  8]]

 [[ 6  7 22]
  [17  5  2]
  [21  5 12]
  [ 3 21  7]]

 [[18 18 14]
  [22 11 30]
  [28  3  9]
  [ 6 17 15]]

 [[22 19  5]
  [ 1 11 24]
  [25 30 14]
  [30 21  4]]

 [[12 18 15]
  [ 2 22 24]
  [12  9 17]
  [30 11  6]]

 [[12 24 21]
  [25 16 15]
  [ 7 10 18]
  [17 17 15]]]


6. Faça o reshape das suas cartelas para que haja 5 cartelas de 4 linhas e 6 colunas

In [16]:
bingo.reshape((5,4,6))

array([[[ 4,  6, 22,  1,  2, 11],
        [14, 18, 24, 14, 18, 18],
        [ 3, 13,  8,  7, 15, 19],
        [23,  4,  1, 16, 16,  7]],

       [[ 4, 15,  9, 29, 18,  5],
        [26, 28,  4, 26, 23, 27],
        [26, 12,  4, 11,  8,  4],
        [20,  1,  3, 22,  2,  1]],

       [[16, 26, 11, 16, 25,  6],
        [30, 18,  9,  8, 16,  8],
        [ 6,  7, 22, 17,  5,  2],
        [21,  5, 12,  3, 21,  7]],

       [[18, 18, 14, 22, 11, 30],
        [28,  3,  9,  6, 17, 15],
        [22, 19,  5,  1, 11, 24],
        [25, 30, 14, 30, 21,  4]],

       [[12, 18, 15,  2, 22, 24],
        [12,  9, 17, 30, 11,  6],
        [12, 24, 21, 25, 16, 15],
        [ 7, 10, 18, 17, 17, 15]]])

Tipos de dados em NumPy vs python

In [17]:
#dtype e tipo default

print ('conversão e coereção')
print ('dtype como argumento:')
arr_float32 = np.array([2.14, 6.25, 160.87], dtype = np.float32)
print(arr_float32)

print ('conversão')
arr_vf = np.array([[True, False], [True, False]], dtype = np.bool_)
print(arr_vf.astype(np.int32))

print ('coerção')
np.array(['pedra', False, 42, 42.42])

conversão e coereção
dtype como argumento:
[  2.14   6.25 160.87]
conversão
[[1 0]
 [1 0]]
coerção


array(['pedra', 'False', '42', '42.42'], dtype='<U32')

In [18]:
print ('Hierarquia de coerção')

print ('adicionar um float a um array de int mudará todo os valores para float')
np.array([0,10]).dtype
print(np)

np.array([0,10,1.]).dtype
print(np)

print ('adicionar um inteiro em um array de booleanos transformará todo o array em inteiros')
np.array([True, False]).dtype
print(np)

np.array([True, False, 12]).dtype
print (np)

Hierarquia de coerção
adicionar um float a um array de int mudará todo os valores para float
<module 'numpy' from 'c:\\Users\\lpgn\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\__init__.py'>
<module 'numpy' from 'c:\\Users\\lpgn\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\__init__.py'>
adicionar um inteiro em um array de booleanos transformará todo o array em inteiros
<module 'numpy' from 'c:\\Users\\lpgn\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\__init__.py'>
<module 'numpy' from 'c:\\Users\\lpgn\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\__init__.py'>


In [19]:
np.array([5.4,6.7,2.1]).dtype

dtype('float64')

In [20]:
np.array([5,6,2]).dtype

dtype('int32')

In [21]:
np.array(['hello', 'oi', 'womakerscode']).dtype

dtype('<U12')

In [22]:
np.array([3,4,2.1]).dtype

dtype('float64')

In [23]:
np.array([True, 3, False]).dtype

dtype('int32')

Index em um array de 1 dimensão

In [24]:
print("a indexação é a ordem dos dados e sempre começa com 0")
arr = np.array ([2,4,6,8])
arr[2]

a indexação é a ordem dos dados e sempre começa com 0


6

In [25]:
print ('para fatiar (slicing) um array de 2 dimensões, deve ser realizado no estilo arr[0:2], onde 0 é o index inicial 2 o index final')
arr[0:2]

para fatiar (slicing) um array de 2 dimensões, deve ser realizado no estilo arr[0:2], onde 0 é o index inicial 2 o index final


array([2, 4])

Index em um array de 2 dimensões

In [26]:
print ("a indexação em um array de 2 dimensões envolve linha x coluna")
arr = np.array([[16,10,3,15], [14,23,17,27], [6,19,3,1], [10,4,18,19]])
arr

a indexação em um array de 2 dimensões envolve linha x coluna


array([[16, 10,  3, 15],
       [14, 23, 17, 27],
       [ 6, 19,  3,  1],
       [10,  4, 18, 19]])

In [27]:
print("indexação de apenas um elemento será no estilo arr[1,3]")
arr[1,3]

indexação de apenas um elemento será no estilo arr[1,3]


27

In [28]:
print ("a indexação de uma linha inteira será no estilo arr[0]")
arr[0]

a indexação de uma linha inteira será no estilo arr[0]


array([16, 10,  3, 15])

In [29]:
print('a indexação de uma coluna inteira será no estilo arr[:,1]')
arr[:,1]

a indexação de uma coluna inteira será no estilo arr[:,1]


array([10, 23, 19,  4])

In [30]:
print ('para fatiar (slicing) um array de 2 dimensões, deve ser realizado no estilo arr[1:3,0:2], onde 1 e 0 é o index inicial e 3 e 2 o index final')
arr[1:3,0:2]

para fatiar (slicing) um array de 2 dimensões, deve ser realizado no estilo arr[1:3,0:2], onde 1 e 0 é o index inicial e 3 e 2 o index final


array([[14, 23],
       [ 6, 19]])

In [31]:
print ('ordenar (sorting) um array trabalha com a ordenação dos elemntos, de forma que cada linha fique com elementos crescentes')
np.sort(arr)

ordenar (sorting) um array trabalha com a ordenação dos elemntos, de forma que cada linha fique com elementos crescentes


array([[ 3, 10, 15, 16],
       [14, 17, 23, 27],
       [ 1,  3,  6, 19],
       [ 4, 10, 18, 19]])

In [32]:
print ('o eixo 0 sempre será a linha horizontal e o eixo 1 sempre será a linha vertical, desta forma pode ser utilizado o eixo para ordenação')
print ('para ordenar com o eixo 0, o eixo horizontal:')
np.sort(arr, axis=0)

o eixo 0 sempre será a linha horizontal e o eixo 1 sempre será a linha vertical, desta forma pode ser utilizado o eixo para ordenação
para ordenar com o eixo 0, o eixo horizontal:


array([[ 6,  4,  3,  1],
       [10, 10,  3, 15],
       [14, 19, 17, 19],
       [16, 23, 18, 27]])

In [33]:
print ('a forma default sempre vai contar com o eixo 1, mas tbm pode ser ordenado da seguinte forma:')
np.sort(arr, axis=1)

a forma default sempre vai contar com o eixo 1, mas tbm pode ser ordenado da seguinte forma:


array([[ 3, 10, 15, 16],
       [14, 17, 23, 27],
       [ 1,  3,  6, 19],
       [ 4, 10, 18, 19]])

7. Explorando ecossistema:
Como bióloga marinha, me encontrei em uma expedição nas profundezas do Oceano Pacífico, onde estávamos estudando a biodiversidade e a saúde dos recifes de coral. O catálogo abaixo demonstra dados das espécies encontradas. Considere a seguinte ordem de colunas:

*ID da espécie, quantidade de representantes encontrados, profundeza, tamanho médio da espécie*

- Selecione a segunda coluna com a quantidade de espécies encontradas e adicione em um array como 'qnt_especies'
- De qnt_especies selecione apenas as primeiras 3 quantidades e print
- Print as 5 últimas quantidades de espécies
- Crie um array que contenha apenas os tamanhos das espécies e ordene por ordem crescente

In [34]:
especies = np.array([
                    [747,  89, 33,  5],
                    [623, 123, 32, 13],
                    [501,  22, 49,  2],
                    [116, 101, 49,  2],
                    [297,  56, 69, 22],
                    [613,  64, 27,  7],
                    [295,  84, 29, 14],
                    [692, 105, 72, 16],
                    [229, 103, 35,  5],
                    [374, 124, 70,  1]
])
especies

array([[747,  89,  33,   5],
       [623, 123,  32,  13],
       [501,  22,  49,   2],
       [116, 101,  49,   2],
       [297,  56,  69,  22],
       [613,  64,  27,   7],
       [295,  84,  29,  14],
       [692, 105,  72,  16],
       [229, 103,  35,   5],
       [374, 124,  70,   1]])

In [35]:
print("Selecione a segunda coluna com a quantidade de espécies encontradas e adicione em um array como 'qnt_especies'")
qnt_especies = especies[:,1]
qnt_especies


Selecione a segunda coluna com a quantidade de espécies encontradas e adicione em um array como 'qnt_especies'


array([ 89, 123,  22, 101,  56,  64,  84, 105, 103, 124])

In [36]:
print("De qnt_especies selecione apenas as primeiras 3 quantidades e print")
qnt_especies[0:3]

De qnt_especies selecione apenas as primeiras 3 quantidades e print


array([ 89, 123,  22])

In [37]:
print("Print as 5 últimas quantidades de espécies")
qnt_especies[-5:]

Print as 5 últimas quantidades de espécies


array([ 64,  84, 105, 103, 124])

In [38]:
print ("Crie um array que contenha apenas os tamanhos das espécies e ordene por ordem crescente")
np.sort(especies[:,3])

Crie um array que contenha apenas os tamanhos das espécies e ordene por ordem crescente


array([ 1,  2,  2,  5,  5,  7, 13, 14, 16, 22])

Filtrando arrays

In [39]:
print ("pode ser por indexação sofisticada (fancy indexing) ou máscara (mask) em array 2d")
pessoas_id_idade = np.array([[1,22], [2,21], [3,27], [4,26]])
print ("exemplo utilizando com máscaras:")
pessoas_id_idade[:,1]%2==0


pode ser por indexação sofisticada (fancy indexing) ou máscara (mask) em array 2d
exemplo utilizando com máscaras:


array([ True, False, False,  True])

In [40]:
print ("boolean mask: returna um array de verdadeiros e falsos")
arr1 = np.array([1,2,3,4,5])
mask = arr1%2==0
mask

boolean mask: returna um array de verdadeiros e falsos


array([False,  True, False,  True, False])

In [41]:
print("fancy indexing: retorna os valores do array quando passado a máscara")
arr1[mask]

fancy indexing: retorna os valores do array quando passado a máscara


array([2, 4])

In [42]:
cartela_bingo = np.array([
                [16, 10,  3, 15],
                [14, 23, 17, 27],
                [ 6, 19,  3,  1], 
                [10,  4, 18, 19]
])

print ("np.wehere() retorna um array de indices, cria uma matriz com base em se os elementos corrspondem ou não a uma condição")

np.where(cartela_bingo % 3 == 0, "", cartela_bingo)

np.wehere() retorna um array de indices, cria uma matriz com base em se os elementos corrspondem ou não a uma condição


array([['16', '10', '', ''],
       ['14', '23', '17', ''],
       ['', '19', '', '1'],
       ['10', '4', '', '19']], dtype='<U11')

In [43]:
np.where(pessoas_id_idade[:,1]%2==0)

(array([0, 3], dtype=int64),)

In [44]:
print(pessoas_id_idade)
print('imprime pessoas maiores de 21 anos')
mask_maior21 = pessoas_id_idade[:,1]>21
print(mask_maior21)
print ('imprime id e idade de pessoas maior que 21')
pessoas_id_idade[mask_maior21]

[[ 1 22]
 [ 2 21]
 [ 3 27]
 [ 4 26]]
imprime pessoas maiores de 21 anos
[ True False  True  True]
imprime id e idade de pessoas maior que 21


array([[ 1, 22],
       [ 3, 27],
       [ 4, 26]])

In [45]:
print('imprime indice dos maiores de 21')
np.where(mask_maior21)

imprime indice dos maiores de 21


(array([0, 2, 3], dtype=int64),)

In [46]:
cartela_bingo

array([[16, 10,  3, 15],
       [14, 23, 17, 27],
       [ 6, 19,  3,  1],
       [10,  4, 18, 19]])

In [48]:
np.where(cartela_bingo%3==0, "div3", cartela_bingo)

array([['16', '10', 'div3', 'div3'],
       ['14', '23', '17', 'div3'],
       ['div3', '19', 'div3', '1'],
       ['10', '4', 'div3', '19']], dtype='<U11')

In [49]:
np.where(pessoas_id_idade>21, "maior de idade", pessoas_id_idade)

array([['1', 'maior de idade'],
       ['2', '21'],
       ['3', 'maior de idade'],
       ['4', 'maior de idade']], dtype='<U14')

8. Ainda usando o array de especie marítima:
- Usando um index booleano crie um array que contém os da maior espécie encontrada (considerando o seu tamanho), esse valor corresponde ao valor 22
- Usando fency index, faça um array que contém apenas dados da espécie com ID 297
- Usando np.where() faça um array com a linha com dados correspondentes a espécie com 105 representantes encontrados
- Considere a profundeza em que a espécie que foi encontrada substitua os valores maiores que 60 com "profundo"

In [53]:
print(especies)

[[747  89  33   5]
 [623 123  32  13]
 [501  22  49   2]
 [116 101  49   2]
 [297  56  69  22]
 [613  64  27   7]
 [295  84  29  14]
 [692 105  72  16]
 [229 103  35   5]
 [374 124  70   1]]


In [54]:
print ("Usando um index booleano crie um array que contém os da maior espécie encontrada (considerando o seu tamanho), esse valor corresponde ao valor 22")
especies[especies[:,3]==22]

Usando um index booleano crie um array que contém os da maior espécie encontrada (considerando o seu tamanho), esse valor corresponde ao valor 22


array([[297,  56,  69,  22]])

In [57]:
print("sando fency index, faça um array que contém apenas dados da espécie com ID 297")
mask_297= especies[:,0]==297
especies[mask_297]

sando fency index, faça um array que contém apenas dados da espécie com ID 297


array([[297,  56,  69,  22]])

In [59]:
print("Usando np.where() faça um array com a linha com dados correspondentes a espécie com 105 representantes encontrados")
especies[np.where(especies[:, 1]==105)]

Usando np.where() faça um array com a linha com dados correspondentes a espécie com 105 representantes encontrados


array([[692, 105,  72,  16]])

In [60]:
print("Considere a profundeza em que a espécie que foi encontrada substitua os valores maiores que 60 com 'profundo'")
np.where(especies[:,2]>60, "Profundo", especies[:,2])

Considere a profundeza em que a espécie que foi encontrada substitua os valores maiores que 60 com 'profundo'


array(['33', '32', '49', '49', 'Profundo', '27', '29', 'Profundo', '35',
       'Profundo'], dtype='<U11')