In [136]:
import numpy as np

In [137]:
l = [1, 2, 3, 4]

In [138]:
arr1 = np.array(l)
arr1

array([1, 2, 3, 4])

In [139]:
#Criando um numpy array do zero
a = np.zeros((2,2)) #recebe uma tupla 2x2
a

array([[0., 0.],
       [0., 0.]])

In [140]:
b = np.arange(0,3) #sinaliza onde inicializa e onde termina -1
b

array([0, 1, 2])

In [141]:
c = np.random.random((3,3)) #recebe uma tupla randonica
c

array([[0.38654666, 0.04402294, 0.59803124],
       [0.0542143 , 0.64259644, 0.68532475],
       [0.60781392, 0.34910421, 0.27264853]])

1. Crie um array com 4 linhas e 3 colunas com valores aleatórios

In [142]:
arrayRandom = np.random.random((4,3))
arrayRandom

array([[0.69392244, 0.06533448, 0.80816305],
       [0.79511124, 0.20673145, 0.296917  ],
       [0.91894282, 0.17913818, 0.29941682],
       [0.38207124, 0.65387148, 0.13076404]])

2. Crie um array com 5 colunas e 10 linhas inicializados com zeros

In [143]:
arrayZero = np.zeros((10,5))
arrayZero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

3. Crie um array com valoes inteiros com 3 linhas e 5 colunas com valores aleatórios

In [144]:
arrayRandomInteiro = np.random.randint(10, 30, size=(3,5)) #valores aleatórios a partir do 10 até 29
arrayRandomInteiro

array([[11, 16, 16, 11, 18],
       [10, 16, 12, 18, 15],
       [18, 11, 28, 22, 14]])

In [145]:
#Array 3D

arr1_2d = np.array([[1,2],[3,4]])
arr2_2d = np.array([[5,6],[7,8]])
arr3_2d = np.array([[9,2],[3,4]])

arr_3d = np.array([arr1_2d, arr2_2d, arr3_2d])
arr_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]],

       [[9, 2],
        [3, 4]]])

In [146]:
#Shape -> quantas dimensões
arrShape = np.zeros((2,4))
print (arrShape)

arrShape.shape

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


(2, 4)

In [147]:
#Flatten -> achatando a matriz
arrFlatten = np.array ([[1,2,3,3], [4,5,6,6], [7,8,9,9]])
print (arrFlatten)

arrFlatten.flatten()

[[1 2 3 3]
 [4 5 6 6]
 [7 8 9 9]]


array([1, 2, 3, 3, 4, 5, 6, 6, 7, 8, 9, 9])

In [148]:
#Reshape -> mudando as dimensões
arrReshape = np.array([[3,4,2], [8,11,5]])
print ('array padrão')
print (arrReshape)

#O reshape sempre deve ser compativel com a quantidade de elementos, por exemplo:
print ('sempre deve ser compativel com a quantidade de elementos, o exemplo acima é 2x3, ou seja, 6 elementos, por isso:')
print ('array 3x2')
print(arrReshape.reshape((3,2)))
print ('array 6x1')
print(arrReshape.reshape((6,1)))

array padrão
[[ 3  4  2]
 [ 8 11  5]]
sempre deve ser compativel com a quantidade de elementos, o exemplo acima é 2x3, ou seja, 6 elementos, por isso:
array 3x2
[[ 3  4]
 [ 2  8]
 [11  5]]
array 6x1
[[ 3]
 [ 4]
 [ 2]
 [ 8]
 [11]
 [ 5]]


4. Reduza o array (5,7) a apenas uma dimensão

In [149]:
array4 = np.zeros((5,7))
print (array4)

print ('transformando para uma dimensão: ')
array4 = array4.flatten()
print(array4)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
transformando para uma dimensão: 
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


5. Considerando que você é uma organizadora de um jogo de bingo, crie um array que irá representar a cartilha desses jogos de bingo. Os números de suas cartelas variam entre 1 a 30, e você terá 10 participantes. Cada cartela terá 12 números (4,3).

Crie um array que represente esse jogo:

In [150]:
bingo = np.random.randint(1,31, size=(10,4,3))
print(bingo)

[[[12 15 12]
  [10  3 27]
  [22 30 13]
  [24 26  5]]

 [[27  7 27]
  [26 13 11]
  [24  9 18]
  [14 23  9]]

 [[ 2 23 28]
  [ 8 20  4]
  [21 22 17]
  [14  4 21]]

 [[18  3 18]
  [30 14 19]
  [17 24  6]
  [20 27 29]]

 [[ 4 29  5]
  [10 25 22]
  [ 2 11  3]
  [24 21  3]]

 [[13 16 11]
  [ 7 11 13]
  [ 3 18 17]
  [ 3 25  8]]

 [[24  6 18]
  [ 5 26  3]
  [ 3 30 18]
  [24 29 15]]

 [[10  4 18]
  [17 10  4]
  [ 6  8 11]
  [22  5 28]]

 [[21 14 23]
  [ 8 16  5]
  [15 29  2]
  [10  9 30]]

 [[26  2 11]
  [ 1  5 21]
  [16 18 17]
  [28 10 19]]]


6. Faça o reshape das suas cartelas para que haja 5 cartelas de 4 linhas e 6 colunas

In [151]:
bingo.reshape((5,4,6))

array([[[12, 15, 12, 10,  3, 27],
        [22, 30, 13, 24, 26,  5],
        [27,  7, 27, 26, 13, 11],
        [24,  9, 18, 14, 23,  9]],

       [[ 2, 23, 28,  8, 20,  4],
        [21, 22, 17, 14,  4, 21],
        [18,  3, 18, 30, 14, 19],
        [17, 24,  6, 20, 27, 29]],

       [[ 4, 29,  5, 10, 25, 22],
        [ 2, 11,  3, 24, 21,  3],
        [13, 16, 11,  7, 11, 13],
        [ 3, 18, 17,  3, 25,  8]],

       [[24,  6, 18,  5, 26,  3],
        [ 3, 30, 18, 24, 29, 15],
        [10,  4, 18, 17, 10,  4],
        [ 6,  8, 11, 22,  5, 28]],

       [[21, 14, 23,  8, 16,  5],
        [15, 29,  2, 10,  9, 30],
        [26,  2, 11,  1,  5, 21],
        [16, 18, 17, 28, 10, 19]]])

Tipos de dados em NumPy vs python

In [152]:
#dtype e tipo default

print ('conversão e coereção')
print ('dtype como argumento:')
arr_float32 = np.array([2.14, 6.25, 160.87], dtype = np.float32)
print(arr_float32)

print ('conversão')
arr_vf = np.array([[True, False], [True, False]], dtype = np.bool_)
print(arr_vf.astype(np.int32))

print ('coerção')
np.array(['pedra', False, 42, 42.42])

conversão e coereção
dtype como argumento:
[  2.14   6.25 160.87]
conversão
[[1 0]
 [1 0]]
coerção


array(['pedra', 'False', '42', '42.42'], dtype='<U32')

In [153]:
print ('Hierarquia de coerção')

print ('adicionar um float a um array de int mudará todo os valores para float')
np.array([0,10]).dtype
print(np)

np.array([0,10,1.]).dtype
print(np)

print ('adicionar um inteiro em um array de booleanos transformará todo o array em inteiros')
np.array([True, False]).dtype
print(np)

np.array([True, False, 12]).dtype
print (np)

Hierarquia de coerção
adicionar um float a um array de int mudará todo os valores para float
<module 'numpy' from 'c:\\Users\\lpgn\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\__init__.py'>
<module 'numpy' from 'c:\\Users\\lpgn\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\__init__.py'>
adicionar um inteiro em um array de booleanos transformará todo o array em inteiros
<module 'numpy' from 'c:\\Users\\lpgn\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\__init__.py'>
<module 'numpy' from 'c:\\Users\\lpgn\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\__init__.py'>


In [154]:
np.array([5.4,6.7,2.1]).dtype

dtype('float64')

In [155]:
np.array([5,6,2]).dtype

dtype('int32')

In [156]:
np.array(['hello', 'oi', 'womakerscode']).dtype

dtype('<U12')

In [157]:
np.array([3,4,2.1]).dtype

dtype('float64')

In [158]:
np.array([True, 3, False]).dtype

dtype('int32')

Index em um array de 1 dimensão

In [159]:
print("a indexação é a ordem dos dados e sempre começa com 0")
arr = np.array ([2,4,6,8])
arr[2]

a indexação é a ordem dos dados e sempre começa com 0


6

In [160]:
print ('para fatiar (slicing) um array de 2 dimensões, deve ser realizado no estilo arr[0:2], onde 0 é o index inicial 2 o index final')
arr[0:2]

para fatiar (slicing) um array de 2 dimensões, deve ser realizado no estilo arr[0:2], onde 0 é o index inicial 2 o index final


array([2, 4])

Index em um array de 2 dimensões

In [161]:
print ("a indexação em um array de 2 dimensões envolve linha x coluna")
arr = np.array([[16,10,3,15], [14,23,17,27], [6,19,3,1], [10,4,18,19]])
arr

a indexação em um array de 2 dimensões envolve linha x coluna


array([[16, 10,  3, 15],
       [14, 23, 17, 27],
       [ 6, 19,  3,  1],
       [10,  4, 18, 19]])

In [162]:
print("indexação de apenas um elemento será no estilo arr[1,3]")
arr[1,3]

indexação de apenas um elemento será no estilo arr[1,3]


27

In [163]:
print ("a indexação de uma linha inteira será no estilo arr[0]")
arr[0]

a indexação de uma linha inteira será no estilo arr[0]


array([16, 10,  3, 15])

In [164]:
print('a indexação de uma coluna inteira será no estilo arr[:,1]')
arr[:,1]

a indexação de uma coluna inteira será no estilo arr[:,1]


array([10, 23, 19,  4])

In [165]:
print ('para fatiar (slicing) um array de 2 dimensões, deve ser realizado no estilo arr[1:3,0:2], onde 1 e 0 é o index inicial e 3 e 2 o index final')
arr[1:3,0:2]

para fatiar (slicing) um array de 2 dimensões, deve ser realizado no estilo arr[1:3,0:2], onde 1 e 0 é o index inicial e 3 e 2 o index final


array([[14, 23],
       [ 6, 19]])

In [166]:
print ('ordenar (sorting) um array trabalha com a ordenação dos elemntos, de forma que cada linha fique com elementos crescentes')
np.sort(arr)

ordenar (sorting) um array trabalha com a ordenação dos elemntos, de forma que cada linha fique com elementos crescentes


array([[ 3, 10, 15, 16],
       [14, 17, 23, 27],
       [ 1,  3,  6, 19],
       [ 4, 10, 18, 19]])

In [167]:
print ('o eixo 0 sempre será a linha horizontal e o eixo 1 sempre será a linha vertical, desta forma pode ser utilizado o eixo para ordenação')
print ('para ordenar com o eixo 0, o eixo horizontal:')
np.sort(arr, axis=0)

o eixo 0 sempre será a linha horizontal e o eixo 1 sempre será a linha vertical, desta forma pode ser utilizado o eixo para ordenação
para ordenar com o eixo 0, o eixo horizontal:


array([[ 6,  4,  3,  1],
       [10, 10,  3, 15],
       [14, 19, 17, 19],
       [16, 23, 18, 27]])

In [168]:
print ('a forma default sempre vai contar com o eixo 1, mas tbm pode ser ordenado da seguinte forma:')
np.sort(arr, axis=1)

a forma default sempre vai contar com o eixo 1, mas tbm pode ser ordenado da seguinte forma:


array([[ 3, 10, 15, 16],
       [14, 17, 23, 27],
       [ 1,  3,  6, 19],
       [ 4, 10, 18, 19]])

7. Explorando ecossistema:
Como bióloga marinha, me encontrei em uma expedição nas profundezas do Oceano Pacífico, onde estávamos estudando a biodiversidade e a saúde dos recifes de coral. O catálogo abaixo demonstra dados das espécies encontradas. Considere a seguinte ordem de colunas:

*ID da espécie, quantidade de representantes encontrados, profundeza, tamanho médio da espécie*

- Selecione a segunda coluna com a quantidade de espécies encontradas e adicione em um array como 'qnt_especies'
- De qnt_especies selecione apenas as primeiras 3 quantidades e print
- Print as 5 últimas quantidades de espécies
- Crie um array que contenha apenas os tamanhos das espécies e ordene por ordem crescente

In [169]:
especies = np.array([
                    [747,  89, 33,  5],
                    [623, 123, 32, 13],
                    [501,  22, 49,  2],
                    [116, 101, 49,  2],
                    [297,  56, 69, 22],
                    [613,  64, 27,  7],
                    [295,  84, 29, 14],
                    [692, 105, 72, 16],
                    [229, 103, 35,  5],
                    [374, 124, 70,  1]
])
especies

array([[747,  89,  33,   5],
       [623, 123,  32,  13],
       [501,  22,  49,   2],
       [116, 101,  49,   2],
       [297,  56,  69,  22],
       [613,  64,  27,   7],
       [295,  84,  29,  14],
       [692, 105,  72,  16],
       [229, 103,  35,   5],
       [374, 124,  70,   1]])

In [170]:
print("Selecione a segunda coluna com a quantidade de espécies encontradas e adicione em um array como 'qnt_especies'")
qnt_especies = especies[:,1]
qnt_especies


Selecione a segunda coluna com a quantidade de espécies encontradas e adicione em um array como 'qnt_especies'


array([ 89, 123,  22, 101,  56,  64,  84, 105, 103, 124])

In [171]:
print("De qnt_especies selecione apenas as primeiras 3 quantidades e print")
qnt_especies[0:3]

De qnt_especies selecione apenas as primeiras 3 quantidades e print


array([ 89, 123,  22])

In [172]:
print("Print as 5 últimas quantidades de espécies")
qnt_especies[-5:]

Print as 5 últimas quantidades de espécies


array([ 64,  84, 105, 103, 124])

In [173]:
print ("Crie um array que contenha apenas os tamanhos das espécies e ordene por ordem crescente")
np.sort(especies[:,3])

Crie um array que contenha apenas os tamanhos das espécies e ordene por ordem crescente


array([ 1,  2,  2,  5,  5,  7, 13, 14, 16, 22])

Filtrando arrays

In [174]:
print ("pode ser por indexação sofisticada (fancy indexing) ou máscara (mask) em array 2d")
pessoas_id_idade = np.array([[1,22], [2,21], [3,27], [4,26]])
print ("exemplo utilizando com máscaras:")
pessoas_id_idade[:,1]%2==0


pode ser por indexação sofisticada (fancy indexing) ou máscara (mask) em array 2d
exemplo utilizando com máscaras:


array([ True, False, False,  True])

In [175]:
print ("boolean mask: returna um array de verdadeiros e falsos")
arr1 = np.array([1,2,3,4,5])
mask = arr1%2==0
mask

boolean mask: returna um array de verdadeiros e falsos


array([False,  True, False,  True, False])

In [176]:
print("fancy indexing: retorna os valores do array quando passado a máscara")
arr1[mask]

fancy indexing: retorna os valores do array quando passado a máscara


array([2, 4])

In [182]:
cartela_bingo = ([
                [16, 10,  3, 15],
                [14, 23, 17, 27],
                [ 6, 19,  3,  1], 
                [10,  4, 18, 19]
])

print ("np.wehere() retorna um array de indices, cria uma matriz com base em se os elementos corrspondem ou não a uma condição")

np.where(cartela_bingo % 3 == 0, "", cartela_bingo)

np.wehere() retorna um array de indices, cria uma matriz com base em se os elementos corrspondem ou não a uma condição


TypeError: unsupported operand type(s) for %: 'list' and 'int'

In [180]:
np.where(pessoas_id_idade[:,1]%2==0)

(array([0, 3], dtype=int64),)

In [185]:
print(pessoas_id_idade)
print('imprime pessoas maiores de 21 anos')
mask_maior21 = pessoas_id_idade[:,1]>21
print(mask_maior21)
print ('imprime id e idade de pessoas maior que 21')
pessoas_id_idade[mask_maior21]

[[ 1 22]
 [ 2 21]
 [ 3 27]
 [ 4 26]]
imprime pessoas maiores de 21 anos
[ True False  True  True]
imprime id e idade de pessoas maior que 21


array([[ 1, 22],
       [ 3, 27],
       [ 4, 26]])

In [187]:
print('imprime indice dos maiores de 21')
np.where(mask_maior21)

imprime indice dos maiores de 21


(array([0, 2, 3], dtype=int64),)