In [2]:
import numpy as np

In [3]:
l = [1, 2, 3, 4]

In [4]:
arr1 = np.array(l)
arr1

array([1, 2, 3, 4])

In [5]:
#Criando um numpy array do zero
a = np.zeros((2,2)) #recebe uma tupla 2x2
a

array([[0., 0.],
       [0., 0.]])

In [6]:
b = np.arange(0,3) #sinaliza onde inicializa e onde termina -1
b

array([0, 1, 2])

In [7]:
c = np.random.random((3,3)) #recebe uma tupla randonica
c

array([[0.22405182, 0.35591072, 0.75514998],
       [0.21171959, 0.1685462 , 0.81520376],
       [0.95458157, 0.49650131, 0.05568327]])

1. Crie um array com 4 linhas e 3 colunas com valores aleatórios

In [8]:
arrayRandom = np.random.random((4,3))
arrayRandom

array([[0.87105551, 0.75159158, 0.63248337],
       [0.93183935, 0.64689046, 0.74979893],
       [0.7944108 , 0.13240564, 0.78595559],
       [0.39841221, 0.33567795, 0.55470676]])

2. Crie um array com 5 colunas e 10 linhas inicializados com zeros

In [9]:
arrayZero = np.zeros((10,5))
arrayZero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

3. Crie um array com valoes inteiros com 3 linhas e 5 colunas com valores aleatórios

In [10]:
arrayRandomInteiro = np.random.randint(10, 30, size=(3,5)) #valores aleatórios a partir do 10 até 29
arrayRandomInteiro

array([[13, 24, 27, 28, 28],
       [22, 11, 16, 11, 20],
       [10, 17, 19, 12, 16]])

In [11]:
#Array 3D

arr1_2d = np.array([[1,2],[3,4]])
arr2_2d = np.array([[5,6],[7,8]])
arr3_2d = np.array([[9,2],[3,4]])

arr_3d = np.array([arr1_2d, arr2_2d, arr3_2d])
arr_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]],

       [[9, 2],
        [3, 4]]])

In [12]:
#Shape -> quantas dimensões
arrShape = np.zeros((2,4))
print (arrShape)

arrShape.shape

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


(2, 4)

In [13]:
#Flatten -> achatando a matriz
arrFlatten = np.array ([[1,2,3,3], [4,5,6,6], [7,8,9,9]])
print (arrFlatten)

arrFlatten.flatten()

[[1 2 3 3]
 [4 5 6 6]
 [7 8 9 9]]


array([1, 2, 3, 3, 4, 5, 6, 6, 7, 8, 9, 9])

In [14]:
#Reshape -> mudando as dimensões
arrReshape = np.array([[3,4,2], [8,11,5]])
print ('array padrão')
print (arrReshape)

#O reshape sempre deve ser compativel com a quantidade de elementos, por exemplo:
print ('sempre deve ser compativel com a quantidade de elementos, o exemplo acima é 2x3, ou seja, 6 elementos, por isso:')
print ('array 3x2')
print(arrReshape.reshape((3,2)))
print ('array 6x1')
print(arrReshape.reshape((6,1)))

array padrão
[[ 3  4  2]
 [ 8 11  5]]
sempre deve ser compativel com a quantidade de elementos, o exemplo acima é 2x3, ou seja, 6 elementos, por isso:
array 3x2
[[ 3  4]
 [ 2  8]
 [11  5]]
array 6x1
[[ 3]
 [ 4]
 [ 2]
 [ 8]
 [11]
 [ 5]]


4. Reduza o array (5,7) a apenas uma dimensão

In [24]:
array4 = np.zeros((5,7))
print (array4)

print ('transformando para uma dimensão: ')
array4 = array4.flatten()
print(array4)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
transformando para uma dimensão: 
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


5. Considerando que você é uma organizadora de um jogo de bingo, crie um array que irá representar a cartilha desses jogos de bingo. Os números de suas cartelas variam entre 1 a 30, e você terá 10 participantes. Cada cartela terá 12 números (4,3).

Crie um array que represente esse jogo:

In [28]:
bingo = np.random.randint(1,31, size=(10,4,3))
print(bingo)

[[[27  2 13]
  [14 19 22]
  [30 15 30]
  [12  7  5]]

 [[17 10 30]
  [ 2 28 13]
  [17  5 14]
  [27  6 10]]

 [[24 12 11]
  [30 28  2]
  [13  2 27]
  [ 1 16  2]]

 [[12 14  8]
  [ 1 16 25]
  [ 8 26 25]
  [19  9  1]]

 [[14 22  6]
  [ 9  3 23]
  [11  3  7]
  [25  8  9]]

 [[20  3 27]
  [29 21 27]
  [27 17  3]
  [28 12  2]]

 [[10  8 29]
  [ 2 20  6]
  [10 12  8]
  [20 11  5]]

 [[15  3 21]
  [12  3  7]
  [ 6 19 22]
  [23 10  8]]

 [[21 25 14]
  [ 7  6 16]
  [16 14 29]
  [ 8  6 27]]

 [[12  5 10]
  [ 8 30 21]
  [25  1 18]
  [10  3 19]]]


6. Faça o reshape das suas cartelas para que haja 5 cartelas de 4 linhas e 6 colunas

In [30]:
bingo.reshape((5,4,6))

array([[[27,  2, 13, 14, 19, 22],
        [30, 15, 30, 12,  7,  5],
        [17, 10, 30,  2, 28, 13],
        [17,  5, 14, 27,  6, 10]],

       [[24, 12, 11, 30, 28,  2],
        [13,  2, 27,  1, 16,  2],
        [12, 14,  8,  1, 16, 25],
        [ 8, 26, 25, 19,  9,  1]],

       [[14, 22,  6,  9,  3, 23],
        [11,  3,  7, 25,  8,  9],
        [20,  3, 27, 29, 21, 27],
        [27, 17,  3, 28, 12,  2]],

       [[10,  8, 29,  2, 20,  6],
        [10, 12,  8, 20, 11,  5],
        [15,  3, 21, 12,  3,  7],
        [ 6, 19, 22, 23, 10,  8]],

       [[21, 25, 14,  7,  6, 16],
        [16, 14, 29,  8,  6, 27],
        [12,  5, 10,  8, 30, 21],
        [25,  1, 18, 10,  3, 19]]])

Tipos de dados em NumPy vs python

In [36]:
#dtype e tipo default

print ('conversão e coereção')
print ('dtype como argumento:')
arr_float32 = np.array([2.14, 6.25, 160.87], dtype = np.float32)
print(arr_float32)

print ('conversão')
arr_vf = np.array([[True, False], [True, False]], dtype = np.bool_)
print(arr_vf.astype(np.int32))

print ('coerção')
np.array(['pedra', False, 42, 42.42])

conversão e coereção
dtype como argumento:
[  2.14   6.25 160.87]
conversão
[[1 0]
 [1 0]]
coerção


array(['pedra', 'False', '42', '42.42'], dtype='<U32')

In [38]:
print ('Hierarquia de coerção')

print ('adicionar um float a um array de int mudará todo os valores para float')
np.array([0,10]).dtype
print(np)

np.array([0,10,1.]).dtype
print(np)

print ('adicionar um inteiro em um array de booleanos transformará todo o array em inteiros')
np.array([True, False]).dtype
print(np)

np.array([True, False, 12]).dtype
print (np)

Hierarquia de coerção
adicionar um float a um array de int mudará todo os valores para float
<module 'numpy' from 'c:\\Users\\lpgn\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\__init__.py'>
<module 'numpy' from 'c:\\Users\\lpgn\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\__init__.py'>
adicionar um inteiro em um array de booleanos transformará todo o array em inteiros
<module 'numpy' from 'c:\\Users\\lpgn\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\__init__.py'>
<module 'numpy' from 'c:\\Users\\lpgn\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\__init__.py'>


In [39]:
np.array([5.4,6.7,2.1]).dtype

dtype('float64')

In [40]:
np.array([5,6,2]).dtype

dtype('int32')

In [41]:
np.array(['hello', 'oi', 'womakerscode']).dtype

dtype('<U12')

In [48]:
np.array([3,4,2.1]).dtype

dtype('float64')

In [44]:
np.array([True, 3, False]).dtype

dtype('int32')