In [2]:
import numpy as np

In [3]:
l = [1, 2, 3, 4]

In [4]:
arr1 = np.array(l)
arr1

array([1, 2, 3, 4])

In [5]:
#Criando um numpy array do zero
a = np.zeros((2,2)) #recebe uma tupla 2x2
a

array([[0., 0.],
       [0., 0.]])

In [6]:
b = np.arange(0,3) #sinaliza onde inicializa e onde termina -1
b

array([0, 1, 2])

In [7]:
c = np.random.random((3,3)) #recebe uma tupla randonica
c

array([[0.22405182, 0.35591072, 0.75514998],
       [0.21171959, 0.1685462 , 0.81520376],
       [0.95458157, 0.49650131, 0.05568327]])

1. Crie um array com 4 linhas e 3 colunas com valores aleatórios

In [8]:
arrayRandom = np.random.random((4,3))
arrayRandom

array([[0.87105551, 0.75159158, 0.63248337],
       [0.93183935, 0.64689046, 0.74979893],
       [0.7944108 , 0.13240564, 0.78595559],
       [0.39841221, 0.33567795, 0.55470676]])

2. Crie um array com 5 colunas e 10 linhas inicializados com zeros

In [9]:
arrayZero = np.zeros((10,5))
arrayZero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

3. Crie um array com valoes inteiros com 3 linhas e 5 colunas com valores aleatórios

In [10]:
arrayRandomInteiro = np.random.randint(10, 30, size=(3,5)) #valores aleatórios a partir do 10 até 29
arrayRandomInteiro

array([[13, 24, 27, 28, 28],
       [22, 11, 16, 11, 20],
       [10, 17, 19, 12, 16]])

In [11]:
#Array 3D

arr1_2d = np.array([[1,2],[3,4]])
arr2_2d = np.array([[5,6],[7,8]])
arr3_2d = np.array([[9,2],[3,4]])

arr_3d = np.array([arr1_2d, arr2_2d, arr3_2d])
arr_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]],

       [[9, 2],
        [3, 4]]])

In [12]:
#Shape -> quantas dimensões
arrShape = np.zeros((2,4))
print (arrShape)

arrShape.shape

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


(2, 4)

In [13]:
#Flatten -> achatando a matriz
arrFlatten = np.array ([[1,2,3,3], [4,5,6,6], [7,8,9,9]])
print (arrFlatten)

arrFlatten.flatten()

[[1 2 3 3]
 [4 5 6 6]
 [7 8 9 9]]


array([1, 2, 3, 3, 4, 5, 6, 6, 7, 8, 9, 9])

In [14]:
#Reshape -> mudando as dimensões
arrReshape = np.array([[3,4,2], [8,11,5]])
print ('array padrão')
print (arrReshape)

#O reshape sempre deve ser compativel com a quantidade de elementos, por exemplo:
print ('sempre deve ser compativel com a quantidade de elementos, o exemplo acima é 2x3, ou seja, 6 elementos, por isso:')
print ('array 3x2')
print(arrReshape.reshape((3,2)))
print ('array 6x1')
print(arrReshape.reshape((6,1)))

array padrão
[[ 3  4  2]
 [ 8 11  5]]
sempre deve ser compativel com a quantidade de elementos, o exemplo acima é 2x3, ou seja, 6 elementos, por isso:
array 3x2
[[ 3  4]
 [ 2  8]
 [11  5]]
array 6x1
[[ 3]
 [ 4]
 [ 2]
 [ 8]
 [11]
 [ 5]]


4. Reduza o array (5,7) a apenas uma dimensão

In [21]:
array4 = np.zeros((5,7))
print (array4)

print ('transformando para uma dimensão: ')
array4.flatten
print(array4)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
transformando para uma dimensão: 
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])