In [2]:
import numpy as np

In [3]:
l = [1, 2, 3, 4]

In [4]:
arr1 = np.array(l)
arr1

array([ 4,  8,  2, 12,  5,  8,  0])

In [7]:
#Criando um numpy array do zero
a = np.zeros((2,2)) #recebe uma tupla 2x2
a

array([[0., 0.],
       [0., 0.]])

In [8]:
b = np.arange(0,3) #sinaliza onde inicializa e onde termina -1
b

array([0, 1, 2])

In [9]:
c = np.random.random((3,3)) #recebe uma tupla randonica
c

array([[0.08384255, 0.88601319, 0.15026148],
       [0.69498266, 0.92223312, 0.45613905],
       [0.00935755, 0.39773874, 0.77853358]])

1. Crie um array com 4 linhas e 3 colunas com valores aleatórios

In [10]:
arrayRandom = np.random.random((4,3))
arrayRandom

array([[0.98722963, 0.05476332, 0.45721481],
       [0.10186472, 0.59252379, 0.79282269],
       [0.66382143, 0.67056192, 0.15857437],
       [0.92845937, 0.97559668, 0.26786407]])

2. Crie um array com 5 colunas e 10 linhas inicializados com zeros

In [13]:
arrayZero = np.zeros((10,5))
arrayZero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

3. Crie um array com valoes inteiros com 3 linhas e 5 colunas com valores aleatórios

In [19]:
arrayRandomInteiro = np.random.randint(10, 30, size=(3,5)) #valores aleatórios a partir do 10 até 29
arrayRandomInteiro

array([[27, 10, 13, 23, 11],
       [14, 22, 19, 26, 16],
       [10, 21, 16, 22, 19]])